### ISSUE TITLE
Import failing when using typescript due to missing files

### ISSUE THREAD

**Issue by cwkang1998** [SoftwareBrothers/admin-bro-firebase-functions#5]
When importing this library according to the docs, it fails because it is unable to find buildHandler. Upon closer inspection, I found that the exports in index.d.ts (./types)does not exists and thus the import has failed. I believe it is suppose to be included as a result of npm build (probably in the CI pipeline), from what I have seen from the other modules with similar code setup as this one.

I did not test this on regular js, only tested it on typescript as of now, but since the index.js in the root directory also imports ./lib/ which do not exists, I think it may have an issue too.

I've tested this with npm, on node version 10 and 12.

**Comment by cwkang1998** [comment]
Tested on yarn, same issue.
![image](https://user-images.githubusercontent.com/23054115/94335918-81f9ae00-0011-11eb-8c99-15cda45ebdaf.png)
No types or lib directory generated for admin-bro-firebase-functions.

![image](https://user-images.githubusercontent.com/23054115/94335969-fc2a3280-0011-11eb-8b20-f2d16dfeb340.png)
Installed admin-bro-sequalize for comparizon, and it has the missing dirs.

**Comment by wojtek-krysiak** [comment]
i will try to fix it during the weekend. Will let you know.

**Comment by cwkang1998** [comment]
Thanks!

**Comment by wojtek-krysiak** [comment]
np - I tested that and it works: https://us-central1-admin-bro-app.cloudfunctions.net/admin/admin :)

the code for the app is here if you need a reference: https://github.com/SoftwareBrothers/admin-bro/tree/beta/app
